### ISSUE TITLE
Sign releases with a common CoreOS key?

### ISSUE THREAD

**Issue by haz-mat** [coreos/terraform-provider-ct#13]
I noticed the releases are signed with @dghubble's key, perhaps. Might be more convenient if the package was signed with a trusted CoreOS app key?

```
gpg: Signature made Thu Aug  3 12:13:54 2017 PDT
gpg:                using RSA key BDFE4DB05D723EDD
gpg: Good signature from "Dalton Hubble <dghubble@gmail.com>" [unknown]
gpg:                 aka "Dalton Hubble <dalton.hubble@coreos.com>" [unknown]
```

Thanks for consideration!

**Comment by dghubble** [comment]
Seems reasonable. `ct` itself recently transitioned from developer signatures to the official application signatures. We should as well in a future release.

**Comment by dghubble** [comment]
These days, I'm maintaining this provider and my signature is about the best trust guarantee I can offer. I hope it provides adequate, but if not, feel free to compile from source!

Some CoreOS projects still use the application signing key (e.g. etcd) when there is a remaining maintainer inside CoreOS/RedHat. I originally made the CoreOS application key hierarchy and do believe it offers advantages over individual signatures (so I agree). But today, I don't know its a reasonable time investment to ask internal folks to build/sign/vouch-for this small project.
