### ISSUE TITLE
terraform-provider-ct: exec format error

### ISSUE THREAD

**Issue by stiller-leser** [coreos/terraform-provider-ct#18]
I am following https://typhoon.psdn.io/google-cloud/ and extracted the provider into a bin-folder within my directory after getting it via wget. However on running terraform plan I get a) asked for the region again and b) * `provider.ct: fork/exec /Users/MY-USERNAME/workspace/bin/terraform-provider-ct: exec format error` is shown.

If I use go get to get the provider I see `module.google-cloud-yavin.module.controllers.data.google_compute_zones.all: data.google_compute_zones.all: googleapi: got HTTP response code 404 with body: Not Found`

Any pointers?

**Comment by dghubble** [comment]
Did you install the Darwin version of `ct` since you appear to be on macOS? Which version? Is it in the location you specified in `~/.terraformrc`?

**Comment by dghubble** [comment]
Closing due to no response.
