### ISSUE TITLE
certificate files

### ISSUE THREAD

**Issue by sean-abbott** [coreos/terraform-provider-ct#29]
I'm trying to get certs installed via ignition and this provider, since the regular ignition provider doesn't support etcd configs.

However, when I try and template the multiline certificates,they don't render appropriately.

Anyone have a suggestion for how to get those done? I can use the templating to create the files with certificates in the core ignition, but not sure how to create those contents via the yaml config....

**Comment by sean-abbott** [comment]
figured out one really hacky way, which is to preserve the spaces inthe tfvars file using heredocs.

Ew.

**Comment by dghubble** [comment]
You may find this related multiline example useful. Template those contents in with Terraform's `template_file`, before passing the content as a `ct_config`.

* https://github.com/poseidon/typhoon/blob/master/aws/container-linux/kubernetes/cl/controller.yaml.tmpl#L118 
* https://github.com/poseidon/typhoon/blob/master/aws/container-linux/kubernetes/controllers.tf#L59

**Comment by sean-abbott** [comment]
Oh, interesting. Perfect. Thanks!
