### ISSUE TITLE
Provider "ct" not available for installation.

### ISSUE THREAD

**Issue by sampcoug** [coreos/terraform-provider-ct#31]
I  installed Terraform on my Macbook and added the binary plugin for my system to ~/.terraform.d/plugins/. 

I am still getting the following error when I run 'terraform init'. Any ideas folks?

`terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "ct" not available for installation.

A provider named "ct" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.`

**Comment by dghubble** [comment]
This is more related to upstream Terraform, but did you name the plugin binary as documented? https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
