### ISSUE TITLE
Readme and Terraform 3rd-party plugin directory

### ISSUE THREAD

**Issue by JordanP** [coreos/terraform-provider-ct#40]
Following the instructions in the Readme didn't work. I had to put this provider binary in the `~/.terraform.d/plugins/linux_amd64` directory. Note the `linux_amd64` part.

**Comment by JordanP** [comment]
This https://github.com/hashicorp/terraform/issues/15705 seems relevant though I confirmed that I had to put the binary in the OS_ARCH subdir.

```
Terraform v0.11.13
+ provider.ct (unversioned)
+ provider.google v2.3.0
+ provider.local v1.2.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0
```

**Comment by dghubble** [comment]
Terraform [docs](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) describe how to use `~/.terraform.d/plugins`. They _also_ allow subdirectories if needed:

> If you use the same plugins directory on multiple systems, you can install plugins into subdirectories...

I've had no issues using the first approach (no arch subdirs). The docs align with Terraform's docs and its what I test against (I'm on Linux as well).

```
tree ~/.terraform.d/plugins/
/home/dghubble/.terraform.d/plugins/
├── terraform-provider-ct_v0.2.1
├── terraform-provider-ct_v0.3.0
├── terraform-provider-ct_v0.3.1
├── terraform-provider-matchbox_v0.2.2
└── terraform-provider-matchbox_v0.2.3
```

If you can't get the usual location to work on your system, you could file an issue with Terraform.

**Comment by JordanP** [comment]
Yeah you were right. Looks like I can't even follow a correct readme.md file :p I am not used to having up-to-date and proper documentation ...
